### 넘파이 ndarray 개요

넘파이 기반 데이터 타입은 ndarray<br>
np.array사용하여 ndarry로 변환시킴

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
array1.shape   

# (3,): 1차원 array로 3개의 데이터를 가지고 있다

(3,)

In [5]:
array2 = np.array([[1,2,3]])
array2.shape

# (1, 3): 1개의 행과 3개의 열로 구성된 2차원 데이터를 가지고 있다
# array1과 동일한 데이터 건수를 가지고 있지만, shape으로 1차원과 2차원임을 구별하고 있음

(1, 3)

In [6]:
array3 = np.array([[1,2,3],[2,3,4]])
array3.shape

# (2, 3): 2차원 array로 2개의 행과 3개의 열로 구성되어 2 * 3 = 6개의 데이터를 가지고 있다

(2, 3)

### ndarray의 데이터 타입

ndarray내의 데이터 타입은 같은 데이터 타입만 가능

In [10]:
list1 = [1,2,3]
array1 = np.array(list1)
array1.dtype

# 같은 데이터 타입으로 이루어진 리스트는 ndarray로 변경 가능

dtype('int32')

서로 다른 데이터 타입이 섞여있는 리스트는 데이터 크기가 큰 타입으로 변경됨

In [70]:
# int와 문자열이 섞인 리스트 변환
list2 = [1, 2, 'test']
array2 = np.array(list2)
array2

# 숫자 1, 2가 문자열 '1', '2'로 변경됨

array(['1', '2', 'test'], dtype='<U11')

In [44]:
# int와 flot이 섞인 리스트 변환
list3 = [1, 2, 3.0]
array3 = np.array(list3)
array3

# 숫자 1, 2가 모두 1., 2. 실수형으로 변경됨

array([1., 2., 3.])

ndarray 내의 데이터 타입 변경은 astype()

In [18]:
# int -> float: 실수형으로 변경되어 소수점 생김
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float -> int: 정수형으로 변경되어 소수점 사라짐
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

테스트용 데이터를 만들거나, 대규모 데이터를 초기화해야 할 경우 사용

arange: array를 range로 표현

In [45]:
sequence_array = np.arange(10)
sequence_array

# 1차원 ndarray 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

zeros

In [46]:
# 튜플 형태의 shape을 입력하면 해당 shape을 가진 0으로 이뤄진 ndarray 반환
zero_array = np.zeros((3,2),dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [47]:
# 튜플 형태의 shape을 입력하면 해당 shape을 가진 1로 이뤄진 ndarray 반환
one_array = np.ones((3,2))
one_array

# dtype을 정해주지 않으면 dafault로 float 설정됨

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### ndarray의 차원과 크기를 변경하는 reshape()

ndarray를 특정 차원 및 크기로 변환

In [71]:
# 1차원 ndarray 생성
array1 = np.arange(10)
print(array1)

# 1차원 -> 2차원으로 변환
array2 = array1.reshape(2,5)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


실전에서는 -1을 인자로 사용 => 알맞은 크기로 알아서 shape 변환해 줌

In [49]:
# 1차원 ndarray 생성
array1 = np.arange(10)
print(array1)

# 5열에 맞는 행을 자동으로 설정해 2차원으로 변환
array2 = array1.reshape(-1,5)
print(array2.shape)

# 1차원 데이터가 10개이므로 5열에 맞는 2행으로 이뤄짐

[0 1 2 3 4 5 6 7 8 9]
(2, 5)


-1 인자는 reshape(-1,1) 형태로 자주 사용<br>
reshape(-1,1): 2차원이고, 여러 개의 행을 가지되 반드시 1개의 열을 가진 ndarray로 변환됨<br>
stack나 concat으로 결합시 각각의 ndarray의 형태를 통일해 사용함<br>

In [59]:
# 1차원 ndarray 생성
array1 = np.arange(8)
print(array1)

# 1차원 -> 2차원으로 변환
array6 = array1.reshape(-1,1)
print(array6.tolist())         # tolist: 리스트로 변환해 줌 -> 리스트로 변환해 출력하면 보기 쉬우므로

[0 1 2 3 4 5 6 7]
[[0], [1], [2], [3], [4], [5], [6], [7]]


In [58]:
# 3차원 ndarray 생성
array3d = array1.reshape((2,2,2))
print(array3d.tolist())

# 3차원 -> 2차원으로 변환
array5 = array3d.reshape(-1,1)
print(array5.tolist())

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

#### 단일값 추출: 타입은 ndarry내의 데이터 타입

1차원

In [72]:
# 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print(array1)

# 3번 데이터 추출
value = array1[2]
print(value)
print(type(value))    # array1[2]의 타입은 ndarray타입이 아닌 ndarray내의 데이터 타입

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [36]:
print(array1[-1],array1[-2])    # 뒤에서 첫 번째와 두 번째 데이터 출력

9 8


In [42]:
# 인덱스 사용해 데이터 수정 가능
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


2차원

In [41]:
# 2차원 ndarray 생성
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])   # 0행 0열
print(array2d[0,1])   # 0행 1열
print(array2d[1,0])   # 1행 0열
print(array2d[2,2])   # 2행 2열

# axis = 0: 행 방향 (default)
# axis = 1: 열 방향

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


#### 슬라이싱

슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출한 데이터 타입은 ndarray 타입

1차원

In [74]:
# 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [75]:
array3 = array1[0:3]  # 0 ~ 2
print(array3)

array4 = array1[:3]  # 0 ~ 2
print(array4)

array5 = array1[3:]  # 3번부터 끝까지
print(array5)

array6 = array1[:]   # 처음부터 끝까지
print(array6)

[1 2 3]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원

In [76]:
# 2차원 ndarray 생성
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
print(array2d[1:3, 0:3])  # 1행~2행, 0열~2열
print(array2d[1:3, :])    
print(array2d[:, :])
print(array2d[:2, 1:])
print(array2d[:2, 0])

[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [62]:
print(array2d[0])  # 0행 
print(array2d[1])  # 1행

[1 2 3]
[4 5 6]


#### 팬시 인덱싱

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [80]:
# 2차원 ndarray 생성
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
array3 = array2d[[0,1], 2]    # (0,2), (1,2) : [0행 2열], [2행 2열]
print(array3.tolist())

array4 = array2d[[0,1], 0:2]  # ((0,0),(0,1), (1,0),(1,1)) : [0행 0열,0행 1열], [1행 0열,1행 1열]
print(array4.tolist())

array5 = array2d[[0,1]]       # ((0, :), (1, :)) : [0행 모든 열], [1행 모든 열]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱

조건 필터링과 검색 동시에 가능<br>
ndarray의 [ ]내에 조건문을 기재

In [68]:
# 1차원 ndarray 생성
array1d = np.arange(start=1, stop=10)

# [ ] 안에 조건문 입력
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [25]:
array1d > 5   # T값을 가진 인덱스 5~8에 해당하는 데이터만 출력

array([False, False, False, False, False,  True,  True,  True,  True])

### 행렬의 정렬 – sort( )와 argsort( )

#### 행렬 정렬

In [28]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬 -> 원본이 아예 변경됨
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [29]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [30]:
# 2차원 행렬의 경우 axis 축 값 설정
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기

np.argsort(): 정렬된 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [31]:
# 오름차순 정렬
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
# 내림차순 정렬
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


argsort는 넘파이 데이터 추출에서 많이 사용됨

In [13]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

#### 행렬 내적(행렬 곱)

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
